version: '3'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: arosaje
      MYSQL_USER: moi
      MYSQL_PASSWORD: moi123
      MYSQL_ROOT_PASSWORD: aaaaaaaa
    volumes:
      - /f/dev/bdd_mspr:/docker-entrypoint-initdb.d

  api:
    build: ./API
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db
