name: arosa_je
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_localization: ^0.2.0
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  go_router: ^13.0.0
  intl: 0.19.0
  gap: ^3.0.1
  get: ^4.6.6
  latlong2: ^0.9.0
  url_launcher: ^6.2.2
  geolocator: ^10.1.0
  flutter_map: ^6.1.0
  flutter_secure_storage: ^9.0.0
  camera: ^0.10.5+9
  path_provider: ^2.1.2
  path: ^1.8.3
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  meta: ^1.10.0
  http: ^1.1.2
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
  json_annotation: ^4.8.1
  http_parser: ^4.0.2
  mocktail: ^1.0.3
  firebase_core: ^2.31.1
  flutter_firebase_chat_core: ^1.6.7
  flutter_chat_ui: ^1.6.13
  flutter_chat_types: ^3.6.2
  cloud_firestore: ^4.17.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.3.9
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.7

flutter:
  uses-material-design: true
  generate: false
  assets:
    - assets/images/icon.png
    - assets/plants/rose.jpg
    - assets/plants/fern.jpg
