name: Build Flutter APK

#on:
#  push:
#    branches:
#      - firebase
#  pull_request:
#    branches:
#      - firebase
on:
    workflow_dispatch:  # Déclenchement manuel

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22'

    - name: Install dependencies
      run: flutter pub get
      working-directory: ./App

    - name: Build APK
      run: flutter build apk --release
      working-directory: ./App

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: A_rosa_je.apk
        path: ./App/apk
